### ISSUE TITLE
Question on Usage

### ISSUE THREAD

**Issue by djgoku** [akirak/git-identity.el#5]
I am trying to use this package but I must be missing something. I followed the configuration [1]. I am not using a global `user.name` or `user.email` or even local `user.name` or `user.email` for repositorie(s).

Lets say this is `git-identity-list` and no global or local `user.name` or `user.email` are set:
```
(setq git-identity-list
      '(("my.personal.address@gmail.com"
         :domains ("github.com")
         ;; The identity is applied if the remote URL contains this organization as directory
         :exclude-organizations ("my-company-org")
         :dirs ("~/.emacs.d" "~/personal"))
        ("my.personal.address@mycompanyorg.com"
         :domains ("github.com")
         ;; The identity is applied if the remote URL contains this organization as directory
         :organizations ("my-company-org"))
        ("my.name@mycompany.com"
         :domains ("mycompany.com")
         :dirs ("~/work"))
        ("liuwenbin@xxx12345.cn"
         ;; Chinese name for cool Chinese sites!
         :name "刘文彬")))
```

- if I open magit in `~/personal/a-repo` the identity chosen should be `my.personal.address@gmail.com` when the `remote.origin.url` does not contain `my-company-org`.
- if I open magit in `~/work/b-repo` the identity chosen should be `my.personal.address@mycompanyorg.com` when `remote.origin.url` contains `my-company-org`.

The above is what I am expecting, but actuality when I check `git-identity-info` in the above cases it shows `User name: nil` and `E-mail: nil`.

Should I be able to use `git-identity.el` with out setting any global or local `user.name` or `user.email` in a repository and have magit select the appropriate identity for the repository I am currently running `magit-status` in currently?

[1] https://github.com/akirak/git-identity.el#configuration

**Comment by akirak** [comment]
Because you have no global identity set, you have to explicit set an identity in every repository you create commits on. In the hydra, you can press `s` to select an identity from your configured identities. You have to configure your identity list first.

If this does not work, please report this issue again.

**Comment by akirak** [comment]
@djgoku Please feel free to re-open this issue if you still have a problem.
