### ISSUE TITLE
Switching config contextually

### ISSUE THREAD

**Issue by Aaronzinhoo** [akirak/git-identity.el#6]
Is this supposed to switch your local git config automatically? Say I have a personal and work GitHub with the hostname ‘github.com’ & ‘aa.github.xx.yy’. Should the git config change automatically or do I switch it manually?

 If it does it automatically is there an example you can provide for my case? I can’t seem to get it to switch automatically.

 If not no worries! love the package!

**Comment by akirak** [comment]
Do you have separate identities for `github.com` and `aa.github.xx.yy` in `git-identity-list`? 

As described in README:

> If you turn on git-identity-magit-mode, git-identity checks for an identity every time magit-commit is invoked. 

A recommended setting is to turn on `git-identity-magit-mode` and remove the e-mail address from your global `gitconfig`. This way you cannot make a commit until you set a local identity (in `.git/config`) in each repository, and git-identity will suggest an identity based on your identity config.

**Comment by Aaronzinhoo** [comment]
My list looks like this:

```
(use-package git-identity
  :after magit
  :bind (:map magit-status-mode-map
              ("I" . git-identity-info))
  :custom
  (git-identity-list
   '(("work@fake.com"
      :domains ("github.xx.yy.zz")
      :dirs ("~/development/work"))
     ("personal@fake.edu"
      :domains ("github.com")
      ;; The identity is applied if the remote URL contains this organization as directory
      :exclude-organizations ("some-org")
      :dirs ("~/.emacs.d" "~/personal"))))
  ;; Warn if the global identity setting violates your policy
  (git-identity-verify t)
  (git-identity-magit-mode t)
  ;; The default user name
  (git-identity-default-username "Aaronzinhoo"))
```

I also have `git-identity-magit-mode`  set as well. I was just curious since maybe I messed up the configuration. 

Also thanks for the other suggestion! I have remove `.gitconfig`. Really appreciate the help and if you notice a problem please let me know!

**Comment by akirak** [comment]
If you still have an issue, please feel free to re-open this ticket.
